name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: source
          submodules: true

      - name: Remove git information and Readme
        run: |
          mkdir AirM2M
          cp -r source/* AirM2M/
          cd AirM2M
          rm -rf .git
          rm -rf README.md

      - name: Compress and Release
        run: |
          zip -r AirM2M.AIR001xx_DFP.${GITHUB_REF#refs/tags/}.pack AirM2M
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.pack"
          allowUpdates: true
